
import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;
import org.omg.PortableInterceptor.SUCCESSFUL;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASLANDGN
 */
public class buy_ticket_frame extends javax.swing.JFrame {

    /**
     * Creates new form buy_ticket_frame
     */
    @SuppressWarnings("FieldMayBeFinal")
    private String Selected_seat = null;

    public String getSelected_seat() {
        return Selected_seat;
    }

    public void setSelected_seat(String Selected_seat) {
        this.Selected_seat = Selected_seat;
    }

    @SuppressWarnings("OverridableMethodCallInConstructor")
    public buy_ticket_frame() {

        initComponents();
        this.setLocationRelativeTo(null);
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        day.removeAllItems();
        month.removeAllItems();
        year.removeAllItems();
        jComboBox1.addItem("select a city");
        jComboBox2.addItem("select a city");
        jComboBox3.removeAllItems();
        jComboBox3.addItem("please choose a seat");
        list1.add("please choose a journey");
        add_cities();
        prepare_date();

    }
    String ids = null;

    public buy_ticket_frame(String id) {

        initComponents();
        this.setLocationRelativeTo(null);
        jComboBox1.removeAllItems();
        day.removeAllItems();
        month.removeAllItems();
        year.removeAllItems();
        jComboBox1.addItem("select a city");
        jComboBox2.removeAllItems();
        jComboBox2.addItem("select a city");
        list1.add("please choose a journey");
        add_cities();
        prepare_date();
        ids = id;
        info(ids);

    }

    private void info(String id) {
        Connection baglanti = null;
        try {

            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            baglanti = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                    "mahkum1905");
            String sorgu = "SELECT * FROM CUSTOMER "
                    + "WHERE CL_ID=" + id;
            Statement komut = baglanti.createStatement();
            ResultSet sonuc = komut.executeQuery(sorgu);
            while (sonuc.next()) {
                name.setText(sonuc.getString("CL_NAME"));
                surname.setText(sonuc.getString("CL_SURNAME"));

            }

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            baglanti.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        list1 = new java.awt.List();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        day = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        name = new javax.swing.JFormattedTextField();
        surname = new javax.swing.JFormattedTextField();
        phone_number = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("bilet");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        list1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        list1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        jButton2.setText("exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("from:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("to:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("git");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("date:");

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setVisible(false);
        jLabel4.setText("VAR");

        jButton4.setText("BUY TICKET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });

        phone_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_numberActionPerformed(evt);
            }
        });

        jLabel5.setText("NAME");

        jLabel6.setText("SURNAME");

        jLabel7.setText("PHONE NUMBER");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton3))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButton4))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String control = list1.getSelectedItem();
        String[] temp = control.split(" ");
        int seat_total = 0;
        Connection baglanti = null;
        try {

            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            baglanti = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                    "mahkum1905");
            String sorgu = "SELECT JR_ID,SEAT_TOTAL,SEAT_LEFT FROM JOURNEY,TRAIN "
                    + "WHERE JOURNEY.TR_ID = TRAIN.TR_ID";
            Statement komut = baglanti.createStatement();
            ResultSet sonuc = komut.executeQuery(sorgu);
            while (sonuc.next()) {
                if (sonuc.getString("JR_ID").contains(temp[0])) {

                    sort_list(list1);
                    seat_total = Integer.parseInt(sonuc.getString("SEAT_TOTAL"));
                    jLabel4.setText("TOTAL SEAT:" + sonuc.getString("SEAT_TOTAL") + "  "
                            + " LEFT:" + sonuc.getString("SEAT_LEFT"));
                    jLabel4.setVisible(true);

                }

            }
            ArrayList<String> a = new ArrayList<String>();
            ArrayList b = new ArrayList();
            for (int i = 0; i < seat_total; i++) {
                a.add(String.valueOf(i + 1));

            }

            sorgu = ("Select *\n from TICKETS "
                    + " WHERE JR_ID=" + temp[0]);
            komut = baglanti.createStatement();
            sonuc = komut.executeQuery(sorgu);
            while (sonuc.next()) {
                b.add(sonuc.getString("SEAT"));
            }

            int[] matches = new int[a.size()];

            int i = 0;
            for (String s : a) {
                if (b.contains(s)) {
                    continue;
                } else {
                    jComboBox3.addItem(s);
                }
            }

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            baglanti.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        list1.removeAll();
        jLabel4.removeAll();
        if (jComboBox1.getSelectedItem().toString().contentEquals("select a city")
                || jComboBox2.getSelectedItem().equals("select a city")) {
            list1.addItem("please choose a journey");
            JOptionPane.showMessageDialog(null, "please select a city", "Information Messgage",
                    JOptionPane.INFORMATION_MESSAGE);

        }
        if (jComboBox1.getSelectedItem().equals("select a city") == false
                && jComboBox2.getSelectedItem().equals("select a city") == false
                && jComboBox1.getSelectedItem().equals(jComboBox2.getSelectedItem())) {
            list1.addItem("please choose a journey");
            JOptionPane.showMessageDialog(null, "there is no journey in same city", "Information Messgage",
                    JOptionPane.INFORMATION_MESSAGE);

        }
        if (jComboBox1.getSelectedItem().equals(jComboBox2.getSelectedItem()) == false) {
            Connection baglanti = null;
            try {
                DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
                baglanti = DriverManager.getConnection(
                        "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                        "mahkum1905");
                String sorgu = ("Select *\n"
                        + "FROM JOURNEY");
                Statement komut = baglanti.createStatement();
                ResultSet sonuc = komut.executeQuery(sorgu);

                while (sonuc.next()) {

                    String[] temp = sonuc.getString("JR_DATE").split("/");
                    if (jComboBox1.getSelectedItem().equals(sonuc.getString("START_POINT"))
                            && jComboBox2.getSelectedItem().equals(sonuc.getString("FINISH_POINT"))
                            && day.getSelectedItem().toString().contains(temp[0])
                            && month.getSelectedItem().toString().contains(temp[1])
                            && year.getSelectedItem().toString().contains(temp[2])) {
                        String control = sonuc.getString("JR_ID")
                                + " " + sonuc.getString("TR_ID")
                                + " " + sonuc.getString("ST_ID")
                                + " " + sonuc.getString("START_POINT")
                                + " " + sonuc.getString("FINISH_POINT")
                                + " " + sonuc.getString("JR_STIME")
                                + " " + sonuc.getString("JR_DATE");
                        list1.addItem(control);
                        
                    }

                    sort_list(list1);
                }
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

            try {
                baglanti.close();
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String temp = list1.getSelectedItem().toString();
        String[] control = temp.split(" ");
        String place = null;
        int seat = 0;
        int seat_total = 0;

        Connection baglanti = null;
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            baglanti = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                    "mahkum1905");
            String sorgu = ("Select *\n from STATION "
                    + " WHERE STATION.ST_ID=" + control[2]);
            Statement komut = baglanti.createStatement();
            ResultSet sonuc = komut.executeQuery(sorgu);
            while (sonuc.next()) {
                place = sonuc.getString("ST_NAME") + " " + sonuc.getString("ST_STATE") + " "
                        + sonuc.getString("ST_CITY");
            }
            sorgu = ("Select *\n from JOURNEY "
                    + " WHERE JOURNEY.JR_ID=" + control[0]);
            sonuc = komut.executeQuery(sorgu);
            komut = baglanti.createStatement();
            while (sonuc.next()) {
                seat = Integer.parseInt(sonuc.getString("SEAT_LEFT"));
            }
            sorgu = ("Select *\n from TRAIN "
                    + " WHERE TRAIN.TR_ID=" + control[1]);
            sonuc = komut.executeQuery(sorgu);
            komut = baglanti.createStatement();
            while (sonuc.next()) {
                seat_total = Integer.parseInt(sonuc.getString("SEAT_TOTAL"));
            }

            if (seat > 0) {

                if (name.getText().isEmpty() == false && name.getText().isEmpty() == false
                        && phone_number.getText().isEmpty() == false) {
                    Selected_seat = String.valueOf(seat_total - seat + 1);
                    seat = seat - 1;
                    PreparedStatement state = baglanti.prepareStatement("UPDATE JOURNEY SET "
                            + "SEAT_LEFT=" + seat + " WHERE JR_ID=" + control[0]);
                    state.executeUpdate();
                    state.close();
                    state = baglanti.prepareStatement("INSERT INTO TICKETS(T_NAME,T_SURNAME,JR_ID,SEAT,PHONE) VALUES"
                            + "('" + name.getText() + "','" + surname.getText() + "',"
                            + control[0] + "," + jComboBox3.getSelectedItem() + "," + phone_number.getText() + ")");
                    state.executeUpdate();
                    state.close();

                    JOptionPane.showMessageDialog(null, "NAME:" + name.getText() + "\nSURNAME:" + surname.getText()
                            + "\nphone number:" + phone_number.getText() + "\nseat:" + jComboBox3.getSelectedItem()
                            + "\nPLACE:" + place, "TICKET INFORMATION",
                            JOptionPane.INFORMATION_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(null, "please fill the blankets", "TICKET INFORMATION",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "no more seat", "TICKET INFORMATION",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block Integer.parseInt(getSelected_seat()) - 1
            e.printStackTrace();
        }

        try {
            baglanti.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void phone_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_numberActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    void prepare_date() {
        for (int i = 1; i < 32; i++) {
            day.addItem(String.valueOf(i));
            if (i < 13) {
                month.addItem(String.valueOf(i));
            }
        }
        for (int i = 2015; i < 2026; i++) {
            year.addItem(String.valueOf(i));
        }
    }

    void sort_list(List list) {

        for (int i = 1; i < list.getItemCount(); i++) {
            String a1 = list.getItem(i);
            String a2 = list.getItem(i - 1);
            if (a1.equals(a2)) {
                list.remove(a1);
            }
        }

    }

    void add_cities() {
        Connection baglanti = null;
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            baglanti = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                    "mahkum1905");
            String sorgu = ("Select *\n"
                    + "FROM STATION");
            Statement komut = baglanti.createStatement();
            ResultSet sonuc = komut.executeQuery(sorgu);
            while (sonuc.next()) {
                jComboBox1.addItem(sonuc.getString("ST_CITY"));
                jComboBox2.addItem(sonuc.getString("ST_CITY"));
            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            baglanti.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> day;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.List list1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JFormattedTextField name;
    private javax.swing.JFormattedTextField phone_number;
    private javax.swing.JFormattedTextField surname;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
