
import java.awt.List;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASLANDGN
 */
public class train_frame extends javax.swing.JFrame {

    /**
     * Creates new form train_frame
     */
    public train_frame() {
        initComponents();
        this.setLocationRelativeTo(null);
        new_train_frame.setVisible(false);
        delete_train_frame.setVisible(false);
        new_train_frame.setSize(500, 350);
        new_train_frame.setLocationRelativeTo(null);
        modify_train_frame.setSize(500, 350);
        modify_train_frame.setLocationRelativeTo(null);
        delete_train_frame.setSize(500, 350);
        delete_train_frame.setLocationRelativeTo(null);
    }
     private void sort_list(List list) {

        for (int i = 1; i < list.getItemCount(); i++) {
            String a1 = list.getItem(i);
            String a2 = list.getItem(i - 1);
            if (a1.equals(a2)) {
                list.remove(a1);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        new_train_frame = new javax.swing.JFrame();
        tr_name = new javax.swing.JFormattedTextField();
        tr_carriage = new javax.swing.JFormattedTextField();
        seat_total = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        modify_train_frame = new javax.swing.JFrame();
        modify_list = new java.awt.List();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        tr_name_m = new javax.swing.JFormattedTextField();
        carr_m = new javax.swing.JFormattedTextField();
        s_tot_m = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        delete_train_frame = new javax.swing.JFrame();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        delete_list = new java.awt.List();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        jLabel1.setText("Tr name");

        jLabel2.setText("carriage");

        jLabel3.setText("seat total");

        jButton3.setText("create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout new_train_frameLayout = new javax.swing.GroupLayout(new_train_frame.getContentPane());
        new_train_frame.getContentPane().setLayout(new_train_frameLayout);
        new_train_frameLayout.setHorizontalGroup(
            new_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_train_frameLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(new_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(new_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(new_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(seat_total)
                        .addComponent(tr_carriage)
                        .addComponent(tr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_train_frameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );
        new_train_frameLayout.setVerticalGroup(
            new_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_train_frameLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(new_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(new_train_frameLayout.createSequentialGroup()
                        .addGroup(new_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(new_train_frameLayout.createSequentialGroup()
                                .addGroup(new_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tr_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tr_carriage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seat_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(75, 75, 75)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jButton8.setText("exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("select");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("modify");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel4.setText("tr name");

        jLabel5.setText("carriage");

        jLabel6.setText("seat total");

        javax.swing.GroupLayout modify_train_frameLayout = new javax.swing.GroupLayout(modify_train_frame.getContentPane());
        modify_train_frame.getContentPane().setLayout(modify_train_frameLayout);
        modify_train_frameLayout.setHorizontalGroup(
            modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modify_train_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modify_train_frameLayout.createSequentialGroup()
                        .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modify_list, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modify_train_frameLayout.createSequentialGroup()
                                .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(modify_train_frameLayout.createSequentialGroup()
                                        .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(55, 55, 55)
                                        .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(s_tot_m, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(carr_m)
                                                .addComponent(tr_name_m, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(39, 39, 39)
                                .addComponent(jButton9)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modify_train_frameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        modify_train_frameLayout.setVerticalGroup(
            modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modify_train_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modify_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modify_train_frameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9))
                    .addGroup(modify_train_frameLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(modify_train_frameLayout.createSequentialGroup()
                                .addComponent(tr_name_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(carr_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(modify_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(s_tot_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(modify_train_frameLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(39, 39, 39)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addContainerGap())
        );

        jButton6.setText("delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout delete_train_frameLayout = new javax.swing.GroupLayout(delete_train_frame.getContentPane());
        delete_train_frame.getContentPane().setLayout(delete_train_frameLayout);
        delete_train_frameLayout.setHorizontalGroup(
            delete_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_train_frameLayout.createSequentialGroup()
                .addGroup(delete_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delete_train_frameLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(delete_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7)
                            .addComponent(jButton6)))
                    .addGroup(delete_train_frameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(delete_list, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        delete_train_frameLayout.setVerticalGroup(
            delete_train_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_train_frameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(delete_list, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("create new train");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("modify train");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("delete train");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 81, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new_train_frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (tr_carriage.getText().isEmpty() == false) {
            Connection baglanti = null;
            try {
                DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
                baglanti = DriverManager.getConnection(
                        "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                        "mahkum1905");
                String sorgu = ("Select * from TRAIN ");
                Statement komut = baglanti.createStatement();
                PreparedStatement state = baglanti.prepareStatement("insert into TRAIN(TR_ID,TR_NAME,TR_CARRIAGE,SEAT_TOTAL)"
                        + "values(TR_ID_SEQ.nextVal,'" + tr_name.getText() + "'," + Integer.parseInt(tr_carriage.getText())
                        + "," + Integer.parseInt(seat_total.getText())
                        + ")");

                state.executeUpdate();
                state.close();
                ResultSet sonuc = komut.executeQuery(sorgu);

                JOptionPane.showMessageDialog(null, "Data Inserted", "Information Messgage",
                        JOptionPane.INFORMATION_MESSAGE);
                baglanti.close();
            } catch (SQLException ex) {
                Logger.getLogger(main_frame.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "something not filled please fill it", "Information Messgage",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        new_train_frame.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        delete_list.removeAll();
        Connection baglanti = null;
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            baglanti = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                    "mahkum1905");
            String sorgu = ("Select *\n"
                    + "FROM TRAIN");
            Statement komut = baglanti.createStatement();
            ResultSet sonuc = komut.executeQuery(sorgu);

            while (sonuc.next()) {

                {
                    String control = sonuc.getString("TR_ID")
                            + "  " + sonuc.getString("TR_NAME")
                            + "  " + sonuc.getString("TR_CARRIAGE")
                            + "  " + sonuc.getString("SEAT_TOTAL");
                    delete_list.addItem(control);

                }

            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            baglanti.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        delete_train_frame.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        delete_train_frame.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        modify_list.removeAll();
        Connection baglanti = null;
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            baglanti = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                    "mahkum1905");
            String sorgu = ("Select *\n"
                    + "FROM TRAIN");
            Statement komut = baglanti.createStatement();
            ResultSet sonuc = komut.executeQuery(sorgu);

            while (sonuc.next()) {

                {
                    String control = sonuc.getString("TR_ID")
                            + "  " + sonuc.getString("TR_NAME")
                            + "  " + sonuc.getString("TR_CARRIAGE")
                            + "  " + sonuc.getString("SEAT_TOTAL");
                    modify_list.addItem(control);

                }

            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            baglanti.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        modify_train_frame.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        modify_train_frame.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String temp = modify_list.getSelectedItem();
        String[] control = temp.split("  ");
        tr_name_m.setText(control[1]);
        carr_m.setText(control[2]);
        s_tot_m.setText(control[3]);

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String temp = modify_list.getSelectedItem();
        String[] control = temp.split("  ");
        Connection baglanti = null;
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());

            baglanti = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                    "mahkum1905");
            PreparedStatement up = baglanti.prepareStatement("UPDATE TRAIN SET TR_NAME='"
                    + tr_name_m.getText() + "',TR_CARRIAGE=" + carr_m.getText()
                    + ",SEAT_TOTAL=" + seat_total.getText()
                    + " WHERE TR_ID=" + control[0]);
            up.executeQuery();
            up.close();
            baglanti.close();
            tr_name_m.setText("");
            carr_m.setText("");
            s_tot_m.setText("");
            JOptionPane.showMessageDialog(null, "Data modified", "Information Messgage",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(employee_frame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Connection baglanti = null;
        try {
            DriverManager.registerDriver(new oracle.jdbc.OracleDriver());
            baglanti = DriverManager.getConnection(
                    "jdbc:oracle:thin:@localhost:1521:xe", "ASLANDGN",
                    "mahkum1905");

            Statement komut = baglanti.createStatement();

            String control = delete_list.getSelectedItem();
            String temp[] = control.split(" ");
            komut.executeUpdate("delete from TRAIN  where TR_ID= '" + temp[0] + "'");
            JOptionPane.showMessageDialog(null, "deleting done...", "Information Messgage",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        try {
            baglanti.close();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField carr_m;
    private java.awt.List delete_list;
    private javax.swing.JFrame delete_train_frame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.List modify_list;
    private javax.swing.JFrame modify_train_frame;
    private javax.swing.JFrame new_train_frame;
    private javax.swing.JFormattedTextField s_tot_m;
    private javax.swing.JFormattedTextField seat_total;
    private javax.swing.JFormattedTextField tr_carriage;
    private javax.swing.JFormattedTextField tr_name;
    private javax.swing.JFormattedTextField tr_name_m;
    // End of variables declaration//GEN-END:variables

}
